services:
  data_collector.cache:
    class: Cache\CacheBundle\DataCollector\CacheDataCollector
    tags:
      - { name: data_collectorr, template: 'CacheBundle:Collector:cache.html.twig', id: 'cache' }

  cache.router_listener:
    class: Cache\CacheBundle\Routing\RouterListener
    arguments: [~, %cache.router.ttl%]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onBeforeRouting, priority: 33 }
      - { name: kernel.event_listener, event: kernel.request, method: onAfterRouting, priority: 31 }
